### ISSUE TITLE
geohash

### ISSUE THREAD

**Issue by whiteCcinn** [zhenbianshu/spatialIndex#1]
方便解释一下，pow(2, 2 * (self::LEVEL_MAX - $level))吗？这里有点不明白。

**Comment by zhenbianshu** [comment]
这个是自己推出来的一个式子， 最小的格子边上是 0.6m，级别值越大格子的边长就越大；
原来的代码有个bug，我已经修复了，应该是 `$range = pow(2, 2 * (self::LEVEL_MAX - $level)) * 0.6;`，少带了一个最小格子的边上。

**Comment by whiteCcinn** [comment]
```php
    /**
     * 通过范围值获取geohash层级
     *
     * @param $range_meter
     *
     * @return int
     */
    private function getLevel($range_meter)
    {
        $level  = 0;
        $global = self::MERCATOR_LENGTH;
        while ($global > $range_meter) {
            $global /= 2;
            $level++;
        }
        return $level;
    }
```

这一段代码的参数应该是km吧，你的`MERCATOR_LENGTH`也是km单位的。

那么

```php
    /**
     * 通过哈希层级获取每一格子的范围
     *
     * @param $level
     *
     * @return number
     */
    private function getLevelRange($level)
    {
        $range = pow(2, 2 * (self::LEVEL_MAX - $level)) * 0.6;
        return $range;
    }
```

这个范围值是不是有点问题？还是说我没理解对。。可以再仔细说说吗？谢谢~

**Comment by zhenbianshu** [comment]
4000多万，是米为单位的。

getLevel 的意思是我从最大一级的格子试起(地球周长)，每次多分割一次，直到分割到不符合传入的 range值了，就获取到此格子级数。

getLevelRange的意思是，已知最小的格子边长是0.6米，格子级数每减小一格，边长就 *2。

**Comment by whiteCcinn** [comment]
@zhenbianshu 喔，对哦，看错了。。
这个那没啥问题了。
这个最小格子的边长是0.6米这个特殊情况是只针对层级为26的情况吗？

**Comment by zhenbianshu** [comment]
对，如果你设置最小层级是27级，那就 0.3m；

**Comment by whiteCcinn** [comment]
@zhenbianshu，好的，谢谢，大神多出点php算法的代码，跟着大神学习。赞。
